name: CI - macOS AppleClang

on:
  push:
    branches: [ "main" ]
    paths: [ 'library/**', 'test/**', 'CMakeLists.txt', '.github/workflows/**' ]
  pull_request:
    branches: [ "main" ]
    paths: [ 'library/**', 'test/**', 'CMakeLists.txt' ]

jobs:
  specialize:
    uses: ./.github/workflows/_compiler_template.yml
    with:
      os: macos-latest
      cxx_compiler: clang++
      display_name: "macOS / Apple Clang"
      